/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppCardLinear: typeof import('./src/components/AppCardLinear/AppCardLinear.vue')['default']
    AppTabBar: typeof import('./src/components/AppTabBar/AppTabBar.vue')['default']
    CheckUpdate: typeof import('./src/components/CheckUpdate.vue')['default']
    CountryPicker: typeof import('./src/components/CountryPicker/CountryPicker.vue')['default']
    LocaleModal: typeof import('./src/components/LocaleModal.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    PageWrap: typeof import('./src/components/PageWrap/PageWrap.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const AppCardLinear: typeof import('./src/components/AppCardLinear/AppCardLinear.vue')['default']
  const AppTabBar: typeof import('./src/components/AppTabBar/AppTabBar.vue')['default']
  const CheckUpdate: typeof import('./src/components/CheckUpdate.vue')['default']
  const CountryPicker: typeof import('./src/components/CountryPicker/CountryPicker.vue')['default']
  const LocaleModal: typeof import('./src/components/LocaleModal.vue')['default']
  const NavBar: typeof import('./src/components/NavBar.vue')['default']
  const PageWrap: typeof import('./src/components/PageWrap/PageWrap.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}