/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppCard: typeof import('./src/components/AppCard/AppCard.vue')['default']
    AppCardLinear: typeof import('./src/components/AppCardLinear/AppCardLinear.vue')['default']
    AppTabBar: typeof import('./src/components/AppTabBar/AppTabBar.vue')['default']
    AppUpdateDialog: typeof import('./src/components/AppUpdateDialog/AppUpdateDialog.vue')['default']
    CheckUpdate: typeof import('./src/components/CheckUpdate.vue')['default']
    CountryPicker: typeof import('./src/components/CountryPicker/CountryPicker.vue')['default']
    CountTo: typeof import('./src/components/CountTo.vue')['default']
    ECharts: typeof import('./src/components/ECharts.vue')['default']
    InviteModal: typeof import('./src/components/InviteModal/InviteModal.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    LocaleModal: typeof import('./src/components/LocaleModal.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    PageWrap: typeof import('./src/components/PageWrap/PageWrap.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanImage: typeof import('vant/es')['Image']
  }
}

// For TSX support
declare global {
  const AppCard: typeof import('./src/components/AppCard/AppCard.vue')['default']
  const AppCardLinear: typeof import('./src/components/AppCardLinear/AppCardLinear.vue')['default']
  const AppTabBar: typeof import('./src/components/AppTabBar/AppTabBar.vue')['default']
  const AppUpdateDialog: typeof import('./src/components/AppUpdateDialog/AppUpdateDialog.vue')['default']
  const CheckUpdate: typeof import('./src/components/CheckUpdate.vue')['default']
  const CountryPicker: typeof import('./src/components/CountryPicker/CountryPicker.vue')['default']
  const CountTo: typeof import('./src/components/CountTo.vue')['default']
  const ECharts: typeof import('./src/components/ECharts.vue')['default']
  const InviteModal: typeof import('./src/components/InviteModal/InviteModal.vue')['default']
  const Loading: typeof import('./src/components/Loading.vue')['default']
  const LocaleModal: typeof import('./src/components/LocaleModal.vue')['default']
  const NavBar: typeof import('./src/components/NavBar.vue')['default']
  const PageWrap: typeof import('./src/components/PageWrap/PageWrap.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const VanImage: typeof import('vant/es')['Image']
}